version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: "blade-formatter"
      - dependency-name: "stillat-blade-parser"

